In [59]:
import pandas as pd

In [60]:
orderlines_df = pd.read_csv("data/raw/orderlines.csv")

In [61]:
orderlines_df

,id,id_order,product_id,product_quantity,sku,unit_price,date
0,1119109,299539,0,1,OTT0133,18.99,2017-01-01 00:07:19
1,1119110,299540,0,1,LGE0043,399.00,2017-01-01 00:19:45
2,1119111,299541,0,1,PAR0071,474.05,2017-01-01 00:20:57
3,1119112,299542,0,1,WDT0315,68.39,2017-01-01 00:51:40
4,1119113,299543,0,1,JBL0104,23.74,2017-01-01 01:06:38
...,...,...,...,...,...,...,...
293978,1650199,527398,0,1,JBL0122,42.99,2018-03-14 13:57:25
293979,1650200,527399,0,1,PAC0653,141.58,2018-03-14 13:57:34
293980,1650201,527400,0,2,APP0698,9.99,2018-03-14 13:57:41
293981,1650202,527388,0,1,BEZ0204,19.99,2018-03-14 13:58:01
293982,1650203,527401,0,1,APP0927,13.99,2018-03-14 13:58:36

In [62]:
orderlines_df.nunique()

id                  293983
id_order            204855
product_id               1
product_quantity        67
sku                   7951
unit_price           11329
date                251631
dtype: int64

In [63]:
orderlines_df = orderlines_df.drop("product_id", axis = 1)

In [64]:
orderlines_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 293983 entries, 0 to 293982
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                293983 non-null  int64
 1   id_order          293983 non-null  int64
 2   product_quantity  293983 non-null  int64
 3   sku               293983 non-null  str
 4   unit_price        293983 non-null  str
 5   date              293983 non-null  str
dtypes: int64(3), str(3)
memory usage: 13.5 MB

In [65]:
orderlines_df.columns = ["id", "order_id", "product_quantity", "sku", "unit_price", "orderlines_date"]

In [66]:
orderlines_df

,id,order_id,product_quantity,sku,unit_price,orderlines_date
0,1119109,299539,1,OTT0133,18.99,2017-01-01 00:07:19
1,1119110,299540,1,LGE0043,399.00,2017-01-01 00:19:45
2,1119111,299541,1,PAR0071,474.05,2017-01-01 00:20:57
3,1119112,299542,1,WDT0315,68.39,2017-01-01 00:51:40
4,1119113,299543,1,JBL0104,23.74,2017-01-01 01:06:38
...,...,...,...,...,...,...
293978,1650199,527398,1,JBL0122,42.99,2018-03-14 13:57:25
293979,1650200,527399,1,PAC0653,141.58,2018-03-14 13:57:34
293980,1650201,527400,2,APP0698,9.99,2018-03-14 13:57:41
293981,1650202,527388,1,BEZ0204,19.99,2018-03-14 13:58:01
293982,1650203,527401,1,APP0927,13.99,2018-03-14 13:58:36

In [67]:
orderlines_df["orderlines_date"] = pd.to_datetime(orderlines_df["orderlines_date"])

In [68]:
orderlines_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 293983 entries, 0 to 293982
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                293983 non-null  int64
 1   order_id          293983 non-null  int64
 2   product_quantity  293983 non-null  int64
 3   sku               293983 non-null  str
 4   unit_price        293983 non-null  str
 5   orderlines_date   293983 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(3), str(2)
memory usage: 13.5 MB

In [69]:
orderlines_df["unit_price"].str.count(r"\.\d\d$").sum()

np.int64(293983)

In [70]:
# creating a new column price_clean to include the corrected price
orderlines_df["price_clean"] = (
    orderlines_df["unit_price"]
    .str.replace(r"\.(?=.*\.)", "", regex=True)
    .astype(float)
)
#  Converting to float & rounding decimal to 2
orderlines_df["price_clean"] = pd.to_numeric(orderlines_df["price_clean"], errors='coerce').round(2)

In [71]:
orderlines_df

,id,order_id,product_quantity,sku,unit_price,orderlines_date,price_clean
0,1119109,299539,1,OTT0133,18.99,2017-01-01 00:07:19,18.99
1,1119110,299540,1,LGE0043,399.00,2017-01-01 00:19:45,399.00
2,1119111,299541,1,PAR0071,474.05,2017-01-01 00:20:57,474.05
3,1119112,299542,1,WDT0315,68.39,2017-01-01 00:51:40,68.39
4,1119113,299543,1,JBL0104,23.74,2017-01-01 01:06:38,23.74
...,...,...,...,...,...,...,...
293978,1650199,527398,1,JBL0122,42.99,2018-03-14 13:57:25,42.99
293979,1650200,527399,1,PAC0653,141.58,2018-03-14 13:57:34,141.58
293980,1650201,527400,2,APP0698,9.99,2018-03-14 13:57:41,9.99
293981,1650202,527388,1,BEZ0204,19.99,2018-03-14 13:58:01,19.99
293982,1650203,527401,1,APP0927,13.99,2018-03-14 13:58:36,13.99

In [72]:
completed_orders = orderlines_df.loc[(orderlines_df["order_id"] == 377561) & (orderlines_df["sku"] == "APP1919"), :]
completed_orders

,id,order_id,product_quantity,sku,unit_price,orderlines_date,price_clean
103477,1316206,377561,1,APP1919,55.99,2017-08-11 09:53:55,55.99
110159,1328322,377561,1,APP1919,37.99,2017-08-30 10:27:13,37.99

TODO: check: very high unit_prices. unit_prices below 0