In [110]:
import pandas as pd

In [111]:
products_df = pd.read_csv("data/raw/products.csv")

In [112]:
products_df

,sku,name,desc,price,promo_price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,499.899,1,8696
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59,589.996,0,13855401
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59,569.898,0,1387
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25,229.997,0,1230
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,31.99,1,1364
...,...,...,...,...,...,...,...
19321,BEL0376,Belkin Travel Support Apple Watch Black,compact and portable stand vertically or horiz...,29.99,269.903,1,12282
19322,THU0060,"Enroute Thule 14L Backpack MacBook 13 ""Black",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392
19323,THU0061,"Enroute Thule 14L Backpack MacBook 13 ""Blue",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392
19324,THU0062,"Enroute Thule 14L Backpack MacBook 13 ""Red",Backpack with capacity of 14 liter compartment...,69.95,649.903,0,1392
19325,THU0063,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392

In [113]:
products_df.loc[products_df["sku"] == "KIN0138"]

,sku,name,desc,price,promo_price,in_stock,type
11086,KIN0138,Kingston microSDHC memory card 32GB UHS Class 1,Memory card microSDHC UHS Class 1 32GB with tr...,13.454,162.793,0,57445397

In [114]:
products_df = products_df.drop_duplicates()

In [115]:
products_df[products_df["sku"].duplicated(keep=False)]

,sku,name,desc,price,promo_price,in_stock,type
7992,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,1729,1305.59,0,1282
8000,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,NaN,1305.59,0,1282

In [116]:
products_df = products_df.drop(8000)

In [117]:
products_df.info()

<class 'pandas.DataFrame'>
Index: 10579 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          10579 non-null  str
 1   name         10579 non-null  str
 2   desc         10572 non-null  str
 3   price        10534 non-null  str
 4   promo_price  10579 non-null  str
 5   in_stock     10579 non-null  int64
 6   type         10529 non-null  str
dtypes: int64(1), str(6)
memory usage: 661.2 KB

In [118]:
products_df["type"] = products_df["type"].str.replace(",", ".")

In [119]:
products_df["type"] = pd.to_numeric(products_df["type"])

In [120]:
products_df.info()

<class 'pandas.DataFrame'>
Index: 10579 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          10579 non-null  str
 1   name         10579 non-null  str
 2   desc         10572 non-null  str
 3   price        10534 non-null  str
 4   promo_price  10579 non-null  str
 5   in_stock     10579 non-null  int64
 6   type         10529 non-null  float64
dtypes: float64(1), int64(1), str(5)
memory usage: 661.2 KB

In [121]:
mask = products_df["price"].astype(str).str.contains(r"\.\d\d\d\.\d\d\d$", na=False)

products_df["price"] = products_df["price"].astype("object")

products_df.loc[mask, "price"] = (
    products_df.loc[mask, "price"]
    .astype(str)
    .str.replace(".", "", regex = False)
    .astype(float)
    / 100000
)

In [122]:
products_df["price"] = pd.to_numeric(products_df["price"])

In [123]:
products_df

,sku,name,desc,price,promo_price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,499.899,1,8696.0
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,589.996,0,13855401.0
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59.00,569.898,0,1387.0
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25.00,229.997,0,1230.0
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,31.99,1,1364.0
...,...,...,...,...,...,...,...
19321,BEL0376,Belkin Travel Support Apple Watch Black,compact and portable stand vertically or horiz...,29.99,269.903,1,12282.0
19322,THU0060,"Enroute Thule 14L Backpack MacBook 13 ""Black",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392.0
19323,THU0061,"Enroute Thule 14L Backpack MacBook 13 ""Blue",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392.0
19324,THU0062,"Enroute Thule 14L Backpack MacBook 13 ""Red",Backpack with capacity of 14 liter compartment...,69.95,649.903,0,1392.0
19325,THU0063,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392.0

In [124]:
products_df = products_df.drop("promo_price", axis = 1)

In [125]:
products_df.to_csv("data/processed/products.csv", index = False)