In [324]:
import pandas as pd

In [325]:
products_df = pd.read_csv("data/raw/products.csv")

In [326]:
products_df

,sku,name,desc,price,promo_price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,499.899,1,8696
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59,589.996,0,13855401
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59,569.898,0,1387
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25,229.997,0,1230
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,31.99,1,1364
...,...,...,...,...,...,...,...
19321,BEL0376,Belkin Travel Support Apple Watch Black,compact and portable stand vertically or horiz...,29.99,269.903,1,12282
19322,THU0060,"Enroute Thule 14L Backpack MacBook 13 ""Black",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392
19323,THU0061,"Enroute Thule 14L Backpack MacBook 13 ""Blue",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392
19324,THU0062,"Enroute Thule 14L Backpack MacBook 13 ""Red",Backpack with capacity of 14 liter compartment...,69.95,649.903,0,1392
19325,THU0063,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392

In [327]:
products_df = products_df.drop_duplicates()

In [328]:
products_df[products_df["sku"].duplicated(keep=False)]

,sku,name,desc,price,promo_price,in_stock,type
7992,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,1729,1305.59,0,1282
8000,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,NaN,1305.59,0,1282

In [329]:
products_df = products_df.drop(8000)

In [330]:
products_df.info()

<class 'pandas.DataFrame'>
Index: 10579 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          10579 non-null  str
 1   name         10579 non-null  str
 2   desc         10572 non-null  str
 3   price        10534 non-null  str
 4   promo_price  10579 non-null  str
 5   in_stock     10579 non-null  int64
 6   type         10529 non-null  str
dtypes: int64(1), str(6)
memory usage: 661.2 KB

In [331]:
products_df["type"] = products_df["type"].str.replace(",", ".")

In [332]:
products_df["type"] = pd.to_numeric(products_df["type"])

In [333]:
products_df.loc[products_df["sku"] == "PAC2313"]

,sku,name,desc,price,promo_price,in_stock,type
15922,PAC2313,Synology DS1517 + NAS Server | 8GB RAM | 60TB ...,NAS server with 8GB RAM and 60TB for Mac and PC,34.187.885,2.759.912,0,12175397.0

In [334]:
products_df.info()

<class 'pandas.DataFrame'>
Index: 10579 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          10579 non-null  str
 1   name         10579 non-null  str
 2   desc         10572 non-null  str
 3   price        10534 non-null  str
 4   promo_price  10579 non-null  str
 5   in_stock     10579 non-null  int64
 6   type         10529 non-null  float64
dtypes: float64(1), int64(1), str(5)
memory usage: 661.2 KB

In [335]:
mask = products_df["price"].astype(str).str.contains(r"\d\d\.\d\d\d\.\d\d\d$", na=False)

products_df["price"] = products_df["price"].astype("object")

products_df.loc[mask, "price"] = (
    products_df.loc[mask, "price"]
    .astype(str)
    .str.replace(".", "", regex = False)
    .astype(float)
    / 10000
)

In [336]:
mask = products_df["price"].astype(str).str.contains(r"\.\d\d\d\.\d\d\d$", na=False)

products_df["price"] = products_df["price"].astype("object")

products_df.loc[mask, "price"] = (
    products_df.loc[mask, "price"]
    .astype(str)
    .str.replace(".", "", regex = False)
    .astype(float)
    / 100000
)

In [337]:
mask = products_df["price"].astype(str).str.contains(r"\d\d\d\.\d\d\d$", na=False)

products_df["price"] = products_df["price"].astype("object")

products_df.loc[mask, "price"] = (
    products_df.loc[mask, "price"]
    .astype(str)
    .str.replace(".", "", regex = False)
    .astype(float)
    / 10000
)

In [338]:
products_df["price"] = pd.to_numeric(products_df["price"])

In [339]:
products_df

,sku,name,desc,price,promo_price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,499.899,1,8696.0
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,589.996,0,13855401.0
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59.00,569.898,0,1387.0
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25.00,229.997,0,1230.0
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,31.99,1,1364.0
...,...,...,...,...,...,...,...
19321,BEL0376,Belkin Travel Support Apple Watch Black,compact and portable stand vertically or horiz...,29.99,269.903,1,12282.0
19322,THU0060,"Enroute Thule 14L Backpack MacBook 13 ""Black",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392.0
19323,THU0061,"Enroute Thule 14L Backpack MacBook 13 ""Blue",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392.0
19324,THU0062,"Enroute Thule 14L Backpack MacBook 13 ""Red",Backpack with capacity of 14 liter compartment...,69.95,649.903,0,1392.0
19325,THU0063,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392.0

In [340]:
products_df = products_df.drop("promo_price", axis = 1)

In [341]:
products_df

,sku,name,desc,price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696.0
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,0,13855401.0
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59.00,0,1387.0
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25.00,0,1230.0
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,1,1364.0
...,...,...,...,...,...,...
19321,BEL0376,Belkin Travel Support Apple Watch Black,compact and portable stand vertically or horiz...,29.99,1,12282.0
19322,THU0060,"Enroute Thule 14L Backpack MacBook 13 ""Black",Backpack with capacity of 14 liter compartment...,69.95,1,1392.0
19323,THU0061,"Enroute Thule 14L Backpack MacBook 13 ""Blue",Backpack with capacity of 14 liter compartment...,69.95,1,1392.0
19324,THU0062,"Enroute Thule 14L Backpack MacBook 13 ""Red",Backpack with capacity of 14 liter compartment...,69.95,0,1392.0
19325,THU0063,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,1,1392.0

In [342]:
products_df = products_df.dropna(subset = ["price"])

In [343]:
products_df.loc[products_df["desc"].isna()]

,sku,name,desc,price,in_stock,type
16126,WDT0211-A,"Open - Purple 2TB WD 35 ""PC Security Mac hard ...",NaN,107.00000,0,1298.0
16128,APP1622-A,Open - Apple Smart Keyboard Pro Keyboard Folio...,NaN,15.68206,0,1298.0
17843,PAC2334,Synology DS718 + NAS Server | 10GB RAM,NaN,566.35000,0,12175397.0
18152,KAN0034-A,Open - Kanex USB-C Gigabit Ethernet Adapter Ma...,NaN,29.99000,0,1298.0
18490,HTE0025,Hyper Pearl 1600mAh battery Mini USB Mirror an...,NaN,24.99000,1,1515.0
18612,OTT0200,OtterBox External Battery Power Pack 20000 mAHr,NaN,79.99000,1,1515.0
18690,HOW0001-A,Open - Honeywell thermostat Lyric zonificador ...,NaN,199.99000,0,11905404.0

In [344]:
products_df.loc[products_df["desc"].isna(), "desc"] = \
    products_df.loc[products_df["desc"].isna(), "name"]

In [345]:
products_df["price"] = products_df["price"].round(2)

In [346]:
products_df.to_csv("data/processed/products.csv", index = False)

In [347]:
products_df

,sku,name,desc,price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696.0
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,0,13855401.0
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59.00,0,1387.0
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25.00,0,1230.0
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,1,1364.0
...,...,...,...,...,...,...
19321,BEL0376,Belkin Travel Support Apple Watch Black,compact and portable stand vertically or horiz...,29.99,1,12282.0
19322,THU0060,"Enroute Thule 14L Backpack MacBook 13 ""Black",Backpack with capacity of 14 liter compartment...,69.95,1,1392.0
19323,THU0061,"Enroute Thule 14L Backpack MacBook 13 ""Blue",Backpack with capacity of 14 liter compartment...,69.95,1,1392.0
19324,THU0062,"Enroute Thule 14L Backpack MacBook 13 ""Red",Backpack with capacity of 14 liter compartment...,69.95,0,1392.0
19325,THU0063,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,1,1392.0

In [348]:
products_df.sample(50)

,sku,name,desc,price,in_stock,type
11890,MAC0129,Macally UC3HUB4C USB Hub-C 4 USB 3.1 ports USB...,Hub connector USB USB-C-A-C and USB port for M...,44.95,1,1.258540e+07
11055,PAC1387,Pack QNAP TS-251 + | 2GB RAM | Seagate 16TB Ir...,Nas QNAP TS-251 + 2GB RAM memory + 16TB (2x8TB...,1068.98,1,1.217540e+07
2823,MYK0022,MyKronoz ZeCircle Black Clock,Smartwatch that monitors sleep for iPhone iPad...,59.00,0,1.190540e+07
12175,APP1575,"Apple MacBook Retina 12 ""Core m3 11GHz | 8GB R...",New MacBook Retina Display 12-inch Core 8GB RA...,1449.00,0,1.282000e+03
12938,MOP0090,Mophie Juice Pack 2.420mAh + Wireless Charging...,Wireless battery cover with 2.420mAh more base...,129.95,0,5.490000e+11
13573,APP1736,42mm Apple Watch Series 2 Aluminum Case and Sp...,Apple Watch 42 mm dual core processor with GPS...,469.00,0,2.489518e+07
18348,LIF0129,LifeProof Fre Case iPhone Waterproof 8/7 Lila,Case submersible in water and resistant to ext...,79.99,1,1.186540e+07
18601,APP2150-A,"Open - Apple iPad Pro 10.5 ""Wi-Fi + Cellular 6...",Pro iPad Wi-Fi + Cellular 64GB and open box,889.00,0,1.064317e+08
2751,BEZ0193,"Be.ez LArobe MacBook Graphite 12 ""Gray / Blue",bicolor Case MacBook 12 inches.,29.90,0,1.383540e+07
816,WDT0196,Western Digital My Book Thunderbolt Duo 6TB Mac,WD External Hard Drive Mac and PC with Thunder...,529.99,0,1.193540e+07
16814,APP2304,"Apple MacBook Pro 13 ""Core i7 Touch Bar 35GHz ...",New MacBook Pro 13 inch Touch Bar 35 GHz Core ...,28.56,0,1.020000e+12
16037,AP20100,Like new - Apple Smart Cover iPad Mini 4 Stone,Polyurethane sheath reconditioned for cases mi...,45.00,1,1.263540e+07
19192,RIN0011,Spotlight Ring Black Wired Wired CCTV camera,wired camera HD with spotlights and two-way co...,229.00,0,9.094000e+03
458,DLK0029,D-Link DCS-5222L surveillance camera,surveillance camera home with 10x zoom feature...,265.99,0,9.094000e+03
14750,APP1959,"Apple MacBook Pro 13 ""Core i5 2GHz | RAM 16GB ...",MacBook Pro 13 inch i5 2GHz RAM 16GB SSD and 5...,2179.00,0,2.158000e+03
5,APP0073,Apple Composite AV Cable iPhone and iPod white,IPhone and iPod AV Cable Dock to Composite Video.,45.00,0,1.230000e+03
18706,DLK0044-A,Open - D-Link DCS-5020L wireless surveillance ...,Reconditioned surveillance camera with Wi-Fi r...,139.99,0,9.094000e+03
11006,PAC1312,Pack QNAP TS-451 + | 8GB RAM | WD 16TB Network,Pack QNAP TS-451 + with 8GB of RAM memory + 16...,1275.99,0,1.217540e+07
12652,HTE0009,Hyper Pearl 3000mAh USB Battery mirror and Silver,Mirror + Portable 3000mAh USB (2.4A) battery c...,34.95,0,1.515000e+03
13464,SPE0166-A,"(Open) Speck SeeThru Case Macbook Pro 13 ""Rosa",Protective polycarbonate shell for MacBook Pro...,49.90,0,1.298000e+03
10736,ICA0055,Incase Systm Smart Case Cover iPhone 6 / 6S Rosa,Double casing layer iPhone 6 / 6s.,34.95,0,1.186540e+07
13438,TUC0293,Tucano DUEINUNO iPhone Case 2 in 1 8 Plus / 7 ...,Case 2 in 1 with removable rear cover and anti...,29.90,0,1.186540e+07
12673,KEN0239,Kensington Support Macbook with fan,Stand with two fans and USB connection for Mac...,39.99,0,8.696000e+03
10661,APP1193,Magnetic charging cable for Apple Watch (2m),Magnetic Cable for Apple Watch load.,45.00,0,2.421540e+07
1585,LAC0149,LaCie 16GB USB 2.0 PenDrive PetitKey,PenDrive 16GB USB 3.0 for Mac and PC submersible.,19.99,0,5.744540e+07
11238,PAC1338,Pack QNAP TS-453A | 8GB RAM | Seagate 12TB Iro...,Pack NAS QNAP TS-453A with 8GB of memory RAM +...,1260.55,0,1.217540e+07
17751,PAC2386,DS418play Synology NAS Server | 2GB RAM | 12TB...,4-bay NAS server to accommodate 4K Ultra HD files,1054.95,0,1.217540e+07
11479,PAC1248,Pack Apple Siri Griffin Survivor Case + Remote...,Pack Remote for Apple TV Media Player Apple Gr...,108.99,1,5.486426e+07
18605,OTT0204,OtterBox USB Cable Twisted Lightning 3 meters,Cable-duty Lightning to USB 3 meters,34.99,1,1.230000e+03
18392,LIF0142,SLAM LifeProof iPhone Case 7 plus / 8 Plus,SLAM falls resistant cover of LifeProof iPhone,59.99,0,1.186540e+07
18549,AP20420,Like new - Apple iPhone 8 Plus 64GB Gold,Apple iPhone 8 Plus Free Refurbished 64GB Colo...,919.00,0,1.132817e+08
18412,APP2643,"Apple iMac Pro 27 ""14-core Intel Xeon W 25GHz ...",Pro iMac 27 inch screen Retina 5K and Intel Xe...,10059.00,0,1.186922e+08
17319,APP2450,Apple Watch the 1st Gen. 38mm Case Stainless s...,Apple Watch the 1st gene. touch screen monitor...,669.00,0,2.488518e+07
12825,JAB0051,Pace Jabra Sport Bluetooth Headphones In-ear Y...,Jabra wireless sports headphones in yellow,99.95,0,5.384000e+03
12293,APP1599,Apple Watch Sport Silver Strap 42mm Yellow,Apple Watch Sport Aluminum Silver 42mm with sp...,419.00,0,2.489518e+07
10659,APP1192,Magnetic charging cable for Apple Watch (30 cm),Magnetic Cable for Apple Watch load.,35.00,1,2.421540e+07
12189,XRI0008,X-Rite ColorMunki Display monitor calibrator,Color calibrator for displays and monitors,187.99,0,1.235540e+07
18039,BEL0319,Belkin iPhone Case SheerForce 8/7 / 6s / 6 Black,sun resistant pouch protects your screen and w...,19.99,1,1.186540e+07
11052,PAC1226,Pack QNAP TS-251 + | 2GB RAM | Seagate 4TB Iro...,Pack NAS QNAP TS-251 + 2GB RAM + 4TB (2x2TB) I...,568.98,0,1.217540e+07
13487,SAN0158,SanDisk Cruzer Dial Flash Drive 16GB USB 2.0,Ultra compact flash drive with built-dial for ...,7.99,0,1.265540e+07
17995,JMO0104,Just Mobile X Quattro Air iPhone Case Black,A sheath without bulky iPhone offers protectio...,29.99,1,1.186540e+07
13424,TRA0019-A,Open - Transcend JetDrive SSD 720 960GB Macboo...,Hard Disk SSD 960GB + Tools Pro Retina 13-inch...,815.00,0,1.298000e+03
17559,AP20334,Like new - Apple iPad mini Smart Cover 4 Red,Polyurethane Smart Cover for iPad Reconditione...,45.00,0,1.263540e+07
1857,TWS0084,Twelve South HiRise Deluxe iPhone and iPad Silver,Lightning adjustable support for iPhone 5 / 5C...,69.99,0,1.216000e+03
12871,PAC2028,Synology DS216 + II | Seagate 4TB IronWolf for...,Synology DS216 + II with 2GB of RAM and 8TB (2...,73.39,0,1.217540e+07
10896,QNA0144,QNAP TS-453U NAS for Mac and PC,4-bay NAS server for small businesses.,906.29,0,1.217540e+07
18004,MOS0233,Moshi iGlaze iPhone Case X Pearl White,elegant bumper case for iPhone X,35.00,1,1.186540e+07
2581,APP1006,"Apple MacBook Pro Retina 15 ""i7 25 Ghz | RAM 1...",New MacBook Pro 15-inch Retina screen Core i7 ...,2609.00,0,1.282000e+03
2579,APP1004,"Apple MacBook Pro Retina 15 ""i7 22GHz | 16GB R...",New MacBook Pro 15-inch Retina screen Core i7 ...,2969.00,0,1.282000e+03
18931,ELG0039-A,Open - Elgato avea Sphere Lamp,Reconditioned Bluetooth lamp multimode control...,99.95,0,5.404000e+03

In [349]:
products_df.loc[products_df["sku"] == "PAC2313"]

,sku,name,desc,price,in_stock,type
15922,PAC2313,Synology DS1517 + NAS Server | 8GB RAM | 60TB ...,NAS server with 8GB RAM and 60TB for Mac and PC,3418.79,0,12175397.0

In [350]:
products_df.sample(100)

,sku,name,desc,price,in_stock,type
13637,ZAG0029,Zagg Invisible Shield Glass Screen Protector i...,Protector Ultra soft edges beveled tempered gl...,19.99,0,1.355540e+07
12985,TPL0024,TP-Link TL-MR6400 Router 4G Wi-Fi N 300Mbps,N wifi router (24GHz) 300Mbps wireless speed,156.09,0,1.334000e+03
12463,PAC1415,Synology DS716 + II Pack | 8GB RAM | WD 6TB Ne...,Synology DS716 + II with 8GB of RAM memory + 6...,809.89,0,1.217540e+07
1093,GTE0035,G-Tech G-RAID Thunderbolt Studio 2 6TB RAID Disk,Technology G-RAID disk 2-bay thunderbolt2.,714.99,0,1.193540e+07
11071,PAC1631,Pack QNAP TS-251 + | 2GB RAM | Seagate NAS 16TB,RAM nas TS-251 + 2 GB memory + 12TB (2x6TB) Ha...,908.98,1,1.217540e+07
...,...,...,...,...,...,...
16319,APP2267,"Apple MacBook Pro 13 ""Core i5 Touch Bar 31GHz ...",New MacBook Pro 13 inch Touch Bar 31 GHz Core ...,2255.59,0,1.020000e+12
11717,STI0007,Stil Mind London FOG Case iPhone 6 / 6S Cobalt...,Stilmind Protective Case for iPhone 6 / 6S,19.99,0,1.186540e+07
18982,NET0025,Arlo Netgear Netgear accessory rechargeable ba...,Rechargeable battery for Netgear Netgear Arlo ...,79.99,0,9.094000e+03
2071,QNA0081,QNAP TS-251 | 4GB RAM Mac and PC Server Nas,2-bay NAS server for Mac and PC.,398.00,0,1.217540e+07
12169,APP1541,Apple Smart Cover iPad Mini 4 Albaricoque,Apple Smart Cover iPad Mini 4 Albaricoque,45.00,0,1.263540e+07