In [177]:
import pandas as pd

In [178]:
products_df = pd.read_csv("data/raw/products.csv")

In [179]:
products_df

,sku,name,desc,price,promo_price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,499.899,1,8696
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59,589.996,0,13855401
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59,569.898,0,1387
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25,229.997,0,1230
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,31.99,1,1364
...,...,...,...,...,...,...,...
19321,BEL0376,Belkin Travel Support Apple Watch Black,compact and portable stand vertically or horiz...,29.99,269.903,1,12282
19322,THU0060,"Enroute Thule 14L Backpack MacBook 13 ""Black",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392
19323,THU0061,"Enroute Thule 14L Backpack MacBook 13 ""Blue",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392
19324,THU0062,"Enroute Thule 14L Backpack MacBook 13 ""Red",Backpack with capacity of 14 liter compartment...,69.95,649.903,0,1392
19325,THU0063,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392

In [180]:
products_df = products_df.drop_duplicates()

In [181]:
products_df

,sku,name,desc,price,promo_price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,499.899,1,8696
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59,589.996,0,13855401
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59,569.898,0,1387
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25,229.997,0,1230
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,31.99,1,1364
...,...,...,...,...,...,...,...
19321,BEL0376,Belkin Travel Support Apple Watch Black,compact and portable stand vertically or horiz...,29.99,269.903,1,12282
19322,THU0060,"Enroute Thule 14L Backpack MacBook 13 ""Black",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392
19323,THU0061,"Enroute Thule 14L Backpack MacBook 13 ""Blue",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392
19324,THU0062,"Enroute Thule 14L Backpack MacBook 13 ""Red",Backpack with capacity of 14 liter compartment...,69.95,649.903,0,1392
19325,THU0063,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392

In [182]:
products_df[products_df["sku"].duplicated(keep=False)]

,sku,name,desc,price,promo_price,in_stock,type
7992,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,1729,1305.59,0,1282
8000,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,NaN,1305.59,0,1282

In [183]:
products_df = products_df.drop(8000)

In [184]:
products_df

,sku,name,desc,price,promo_price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,499.899,1,8696
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59,589.996,0,13855401
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59,569.898,0,1387
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25,229.997,0,1230
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,31.99,1,1364
...,...,...,...,...,...,...,...
19321,BEL0376,Belkin Travel Support Apple Watch Black,compact and portable stand vertically or horiz...,29.99,269.903,1,12282
19322,THU0060,"Enroute Thule 14L Backpack MacBook 13 ""Black",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392
19323,THU0061,"Enroute Thule 14L Backpack MacBook 13 ""Blue",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392
19324,THU0062,"Enroute Thule 14L Backpack MacBook 13 ""Red",Backpack with capacity of 14 liter compartment...,69.95,649.903,0,1392
19325,THU0063,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392

In [185]:
products_df.info()

<class 'pandas.DataFrame'>
Index: 10579 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          10579 non-null  str
 1   name         10579 non-null  str
 2   desc         10572 non-null  str
 3   price        10534 non-null  str
 4   promo_price  10579 non-null  str
 5   in_stock     10579 non-null  int64
 6   type         10529 non-null  str
dtypes: int64(1), str(6)
memory usage: 661.2 KB

In [186]:
orderlines_df = pd.read_csv("data/raw/orderlines.csv")

In [187]:
orderlines_df["unit_price"] = orderlines_df["unit_price"].str.replace(".", "")

In [188]:
orderlines_df["unit_price"] = pd.to_numeric(orderlines_df["unit_price"])

In [189]:
combined_df = products_df.merge(orderlines_df, on="sku", how = "outer")

In [190]:
combined_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 296712 entries, 0 to 296711
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   sku               296712 non-null  str
 1   name              295294 non-null  str
 2   desc              295280 non-null  str
 3   price             295148 non-null  str
 4   promo_price       295294 non-null  str
 5   in_stock          295294 non-null  float64
 6   type              295074 non-null  str
 7   id                293983 non-null  float64
 8   id_order          293983 non-null  float64
 9   product_id        293983 non-null  float64
 10  product_quantity  293983 non-null  float64
 11  unit_price        293983 non-null  float64
 12  date              293983 non-null  str
dtypes: float64(6), str(7)
memory usage: 29.4 MB

In [191]:
combined_df.groupby("sku")["unit_price"].nunique()

sku
8MO0001-A    1
8MO0003-A    1
8MO0007      2
8MO0008      2
8MO0009      5
            ..
ZAG0041      1
ZAG0042      1
ZEP0007      2
ZEP0008      1
par0072      6
Name: unit_price, Length: 10680, dtype: int64

In [192]:
(
    combined_df[["sku", "name", "price", "promo_price", "unit_price"]]
 .groupby(["sku", "name", "price", "promo_price"])
 .agg(unit_price_max=("unit_price", "max"),
      unit_price_min=("unit_price", "min"))
 )

,,,,unit_price_max,unit_price_min
sku,name,price,promo_price,,
8MO0001-A,"Open - Micro SD Adapter 8Mobility iSlice Macbook Air 13 ""Silver",35,129.619,1296.0,1296.0
8MO0003-A,"Open - 8Mobility iSlice Micro SD adapter for Macbook Retina 15 ""Mid 2012 / Early 2013 Silver",35,128.515,1285.0,1285.0
8MO0007,"8Mobility iSlice Micro SD adapter for Macbook Air 13 ""Silver",35,239.895,2399.0,1999.0
8MO0008,"8Mobility iSlice Micro SD Adapter Macbook Pro Retina 13 ""Silver",35,199.904,2399.0,1999.0
8MO0009,"8Mobility iSlice Micro SD Adapter for Macbook Pro Retina 15 ""Mid 2012 / Early 2013 Silver",35,149.895,2399.0,1470.0
...,...,...,...,...,...
ZAG0041,Zagg iPhone Glass Screen Protector + 8 Plus / 7 Plus / 6s Plus / 6 Plus,29.99,199.904,1999.0,1999.0
ZAG0042,Zagg Glass Screen Protector + iPhone 8/7 / 6 / 6S,29.99,199.904,1999.0,1999.0
ZEP0007,Zepp Golf Golf Amarillo Sensor Kit,149.99,125.99,13990.0,12599.0
ZEP0008,Zepp Tennis Tennis Yellow Sensor Kit,149.99,125.99,10412.0,10412.0
par0072,Parrot AR Drone 2.0 Elite Edition cuadricóptero Black,349,2.099.895,26999.0,19799.0

In [193]:
(
    combined_df[
        combined_df["price"].astype(str).str.contains(r"\.\d\d$", regex=True)
    ][["sku", "name", "price", "unit_price"]]
    .groupby(["sku", "name", "price"])
    .agg(
        unit_price_max=("unit_price", "max"),
        unit_price_min=("unit_price", "min")
    )
)

,,,unit_price_max,unit_price_min
sku,name,price,,
ACM0008,"Acme Skinny Sleeve ""brown / Case MacBook Air 11 Turquoise",34.95,NaN,NaN
ACM0009,"Acme Skinny Sleeve Case MacBook Air 11 ""Black",34.95,2699.0,2399.0
ACM0011,"Acme Skinny Sleeve Case MacBook Air 13 ""Black / Orange",34.95,NaN,NaN
ACM0033,"Acme Skinny Sleeve Case MacBook Air / Pro 13 ""Black",34.95,2399.0,2399.0
ACM0034,"Acme Skinny Sleeve Case MacBook Air 13 ""Purple / Blue",34.95,NaN,NaN
...,...,...,...,...
ZAG0040,Zagg Glass Screen Protector + Contour Contour iPhone X Clear and Black,39.99,2999.0,2699.0
ZAG0041,Zagg iPhone Glass Screen Protector + 8 Plus / 7 Plus / 6s Plus / 6 Plus,29.99,1999.0,1999.0
ZAG0042,Zagg Glass Screen Protector + iPhone 8/7 / 6 / 6S,29.99,1999.0,1999.0
ZEP0007,Zepp Golf Golf Amarillo Sensor Kit,149.99,13990.0,12599.0
ZEP0008,Zepp Tennis Tennis Yellow Sensor Kit,149.99,10412.0,10412.0

In [194]:
combined_df_test = (
    combined_df[
        combined_df["price"].astype(str).str.contains(r"\.\d\d\d$", regex=True)
    ][["sku", "name", "price", "unit_price"]]
    .groupby(["sku", "name", "price"])
    .agg(
        unit_price_max=("unit_price", "max"),
        unit_price_min=("unit_price", "min")
    )
)

combined_df_test
# remove points and divide by 10000

,,,unit_price_max,unit_price_min
sku,name,price,,
ADN0023-A,Open - Adonit Jot Stylus Black Mini 2.0,199.904,1681.0,1681.0
AII0093-A,(Open) Silicone Keyboard Protector Aiino Macbook Air / Pro Black,199.904,NaN,NaN
APP0660-A,"Open - AppleCare Protection MacBook Pro 15 """,3.490.003,25311.0,25311.0
APP0672,Apple iPhone 5S 16GB Space Gray,4.694.994,NaN,NaN
APP0673,Apple iPhone 5S 16GB Silver,4.090.042,NaN,NaN
...,...,...,...,...
WDT0185,"Red 750GB WD 25 ""Mac PC hard drive and NAS",639.896,4999.0,4999.0
WDT0240,"Western Digital 3TB Hard Drive 35 """,2.199.901,NaN,NaN
WDT0284,Western Digital My Passport For Mac Black 1TB Hard Drive for Mac,78.794,NaN,NaN
WDT0400,WD My Cloud Home 3TB USB 3.0,2.049.946,21279.0,20499.0
WIT0011-A,Open - Withings Blood Pressure Monitor Wireless iPhone iPad and iPod touch,92.197.644,9220.0,9220.0

In [195]:
print(combined_df_test.index.names)

['sku', 'name', 'price']

In [196]:
combined_df_test = combined_df_test.reset_index()

In [197]:
combined_df_test["price"] = (
    combined_df_test["price"]
    .str.replace(".", "", regex = False)
    .astype(float)
    / 10000
)

In [198]:
combined_df_test

,sku,name,price,unit_price_max,unit_price_min
0,ADN0023-A,Open - Adonit Jot Stylus Black Mini 2.0,19.9904,1681.0,1681.0
1,AII0093-A,(Open) Silicone Keyboard Protector Aiino Macbo...,19.9904,NaN,NaN
2,APP0660-A,"Open - AppleCare Protection MacBook Pro 15 """,349.0003,25311.0,25311.0
3,APP0672,Apple iPhone 5S 16GB Space Gray,469.4994,NaN,NaN
4,APP0673,Apple iPhone 5S 16GB Silver,409.0042,NaN,NaN
...,...,...,...,...,...
537,WDT0185,"Red 750GB WD 25 ""Mac PC hard drive and NAS",63.9896,4999.0,4999.0
538,WDT0240,"Western Digital 3TB Hard Drive 35 """,219.9901,NaN,NaN
539,WDT0284,Western Digital My Passport For Mac Black 1TB ...,7.8794,NaN,NaN
540,WDT0400,WD My Cloud Home 3TB USB 3.0,204.9946,21279.0,20499.0
541,WIT0011-A,Open - Withings Blood Pressure Monitor Wireles...,9219.7644,9220.0,9220.0

In [199]:
combined_df_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sku             542 non-null    str
 1   name            542 non-null    str
 2   price           542 non-null    float64
 3   unit_price_max  319 non-null    float64
 4   unit_price_min  319 non-null    float64
dtypes: float64(3), str(2)
memory usage: 21.3 KB

In [200]:
(
    combined_df[
        ~combined_df["price"].astype(str).str.contains(r"\.")
    ][["sku", "name", "price", "unit_price"]]
    .groupby(["sku", "name", "price"])
    .agg(
        unit_price_max=("unit_price", "max"),
        unit_price_min=("unit_price", "min")
    )
)

,,,unit_price_max,unit_price_min
sku,name,price,,
8MO0001-A,"Open - Micro SD Adapter 8Mobility iSlice Macbook Air 13 ""Silver",35,1296.0,1296.0
8MO0003-A,"Open - 8Mobility iSlice Micro SD adapter for Macbook Retina 15 ""Mid 2012 / Early 2013 Silver",35,1285.0,1285.0
8MO0007,"8Mobility iSlice Micro SD adapter for Macbook Air 13 ""Silver",35,2399.0,1999.0
8MO0008,"8Mobility iSlice Micro SD Adapter Macbook Pro Retina 13 ""Silver",35,2399.0,1999.0
8MO0009,"8Mobility iSlice Micro SD Adapter for Macbook Pro Retina 15 ""Mid 2012 / Early 2013 Silver",35,2399.0,1470.0
...,...,...,...,...
XRI0010,X-Rite ColorMunki Photo + GrafiLite Free,613,NaN,NaN
XTO0005-A,Open - Xtorm Power Case 4000mAh Battery Case Black iPhone 6 Plus,79,NaN,NaN
XTO0011,Xtorm Power Case 4000mAh Battery Case Black iPhone 6 Plus,79,5699.0,5699.0
XTO0012,Xtorm XB103 Qi Wireless Power Bank Fast charge,79,6499.0,5123.0
par0072,Parrot AR Drone 2.0 Elite Edition cuadricóptero Black,349,26999.0,19799.0

In [203]:
products_df["type"] = products_df["type"].str.replace(",", ".")

In [204]:
products_df["type"] = pd.to_numeric(products_df["type"])

In [205]:
products_df.info()

<class 'pandas.DataFrame'>
Index: 10579 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          10579 non-null  str
 1   name         10579 non-null  str
 2   desc         10572 non-null  str
 3   price        10534 non-null  str
 4   promo_price  10579 non-null  str
 5   in_stock     10579 non-null  int64
 6   type         10529 non-null  float64
dtypes: float64(1), int64(1), str(5)
memory usage: 661.2 KB

In [170]:
mask = products_df["price"].astype(str).str.contains(r"\.\d\d\d$", na=False)

products_df["price"] = products_df["price"].astype("object")

products_df.loc[mask, "price"] = (
    products_df.loc[mask, "price"]
    .astype(str)
    .str.replace(".", "", regex = False)
    .astype(float)
    / 10000
)

In [171]:
products_df

,sku,name,desc,price,promo_price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,499.899,1,8696.0
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59,589.996,0,13855401.0
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59,569.898,0,1387.0
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25,229.997,0,1230.0
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,31.99,1,1364.0
...,...,...,...,...,...,...,...
19321,BEL0376,Belkin Travel Support Apple Watch Black,compact and portable stand vertically or horiz...,29.99,269.903,1,12282.0
19322,THU0060,"Enroute Thule 14L Backpack MacBook 13 ""Black",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392.0
19323,THU0061,"Enroute Thule 14L Backpack MacBook 13 ""Blue",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392.0
19324,THU0062,"Enroute Thule 14L Backpack MacBook 13 ""Red",Backpack with capacity of 14 liter compartment...,69.95,649.903,0,1392.0
19325,THU0063,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392.0

In [172]:
products_df["price"] = pd.to_numeric(products_df["price"])

In [173]:
products_df

,sku,name,desc,price,promo_price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,499.899,1,8696.0
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,589.996,0,13855401.0
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59.00,569.898,0,1387.0
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25.00,229.997,0,1230.0
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,31.99,1,1364.0
...,...,...,...,...,...,...,...
19321,BEL0376,Belkin Travel Support Apple Watch Black,compact and portable stand vertically or horiz...,29.99,269.903,1,12282.0
19322,THU0060,"Enroute Thule 14L Backpack MacBook 13 ""Black",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392.0
19323,THU0061,"Enroute Thule 14L Backpack MacBook 13 ""Blue",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392.0
19324,THU0062,"Enroute Thule 14L Backpack MacBook 13 ""Red",Backpack with capacity of 14 liter compartment...,69.95,649.903,0,1392.0
19325,THU0063,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392.0

TODO: merge products_df with orderlines_df and compare prices /n
TODO: convert type to numeric -> Martin

In [201]:
products_df["sku"] = products_df["sku"].str.replace("AP2", "APP")

In [202]:
products_df[products_df["sku"].duplicated(keep=False)]

,sku,name,desc,price,promo_price,in_stock,type
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59,589.996,0,13855401
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59,569.898,0,1387
9,APP0100,Apple Adapter Mini Display Port to VGA,Adapter Mini Display Port to VGA MacBook and M...,35,330.003,0,1325
10,APP0101,Apple Mini DisplayPort to DVI Adapter,Adapter mini DisplayPort to DVI MacBook and Ma...,35,330.003,0,1325
12,APP0111,Apple USB Ethernet Adapter Mac,USB to Ethernet adapter Mac.,35,330.003,0,1334
...,...,...,...,...,...,...,...
18570,APP0437,"Like new - Apple MacBook Pro Retina 13 ""i5 27 ...",MacBook reconditioned 13 inch i5 to 27GHz with...,1689,13.955.946,0,"2,17E+11"
18575,APP0431,"Like new - Apple iMac 215 ""Core i5 Dual 23GHz ...",IMac reconditioned 215 inch i5 23GHz,1305.59,10.955.945,0,1282
18576,APP0436,"Like new - Apple iMac 215 ""4K Retina Quad Core...",IMac reconditioned 215 inch 4K Retina Quad i5 ...,1505.59,12.455.946,0,1282
19200,APP0390,Like new - Apple iPad Wi-Fi + Cellular 128GB S...,iPad Wi-Fi + Cellular Refurbished 128GB in Silver,662.81,5.528.115,0,12141714
19290,APP0474,Like new - Apple Watch GPS 38mm Case Series 3 ...,Reconditioned Apple Watch 38mm series 3 with G...,369,3.189.996,0,24885185